"""Build supplementary uncertainty tables for locked KP-BSI model results."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


HELP = """Function
  Build supplementary paired-bootstrap statistics from the locked KP-BSI model outputs. The script reads nested-model predictions, recomputes the hypervirulence-marker encoding comparison from the model-ready feature table, and writes one plain supplementary table package.

Required Arguments
  --run
      Explicitly confirms that the script should execute. Running with no arguments prints this help and exits without doing work.

Optional Arguments
  --clinical-selection PATH
      Training-only selection record; by default read clinical_selection.json beside ladder predictions.
  --features PATH
      Model-ready feature table. Default: 02_features/analysis_datasets/merged_full.csv.
  --ladder-predictions PATH
      Locked nested-model per-patient predictions. Default: nested_information_models output.
  --output-dir PATH
      Primary output directory. Default: submit/table.
  --bootstrap N
      Number of patient-level bootstrap resamples. Default: 2000.
  --seed N
      Random seed for bootstrap resampling. Default: 42.
  --update-figure2-source
      Also refresh submit/figure/source_data/figure2_marker_encoding_auroc_source.csv with split-specific AUROC bootstrap estimates.
  --overwrite
      Allow replacing files generated by this script.
  -h, --help
      Show this help text.

Output
  Primary output path: --output-dir. The script writes source_data CSV files, supplementary_model_uncertainty_statistics.xlsx, supplementary_model_uncertainty_statistics.md, and supplementary_model_uncertainty_manifest.json.
"""


OUTCOMES = ["death_30d", "metastatic"]
OUTCOME_LABELS_FOR_TABLE = {
    "mortality_30d": "30-day mortality",
    "metastatic_infection": "Liver abscess or metastatic infection",
}
TEST_SPLIT = "test_2024_2025"
VALIDATION_SPLIT = "validation_2022_2023"
LADDER_AST_COL = "clinical_ast_prob"
LADDER_FULL_COL = "clinical_ast_markers_gwas_prob"
FIVE_MARKER_MODELS = {
    "baseline": "baseline_prob",
    "five_markers_separate": "five_markers_separate_prob",
    "five_marker_binary_all_partial": "five_marker_binary_all_partial_prob",
}
FIVE_MARKER_LABELS = {
    "baseline": "Baseline",
    "five_markers_separate": "+ individual markers",
    "five_marker_binary_all_partial": "+ compressed status",
}
METRIC_DIRECTIONS = {
    "AUROC": "higher is better",
    "AUPRC": "higher is better",
    "Brier": "lower is better",
    "LogLoss": "lower is better",
}


@dataclass(frozen=True)
class Paths:
    features: Path
    ladder_predictions: Path
    output_dir: Path


def project_root() -> Path:
    return Path(__file__).resolve().parents[3]


def default_paths() -> Paths:
    root = project_root()
    model_dir = root / "03_models" / "clinical_genomic_models"
    return Paths(
        features=root / "02_features" / "analysis_datasets" / "merged_full.csv",
        ladder_predictions=model_dir
        / "model_outputs"
        / "nested_information_models"
        / "ladder_predictions.csv",
        output_dir=root / "submit" / "table",
    )


def parse_args(argv: list[str]) -> argparse.Namespace | None:
    defaults = default_paths()
    if not argv:
        print(HELP)
        return None

    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--clinical-selection", type=Path)
    parser.add_argument("--features", type=Path, default=defaults.features)
    parser.add_argument("--ladder-predictions", type=Path, default=defaults.ladder_predictions)
    parser.add_argument("--output-dir", type=Path, default=defaults.output_dir)
    parser.add_argument("--bootstrap", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--update-figure2-source", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("-h", "--help", action="store_true")
    args, unknown = parser.parse_known_args(argv)

    if args.help:
        print(HELP)
        return None
    if unknown or not args.run:
        print(HELP, file=sys.stderr)
        if unknown:
            print(f"Unknown arguments: {' '.join(unknown)}", file=sys.stderr)
        if not args.run:
            print("Missing required argument: --run", file=sys.stderr)
        raise SystemExit(2)
    if args.bootstrap <= 0:
        raise SystemExit("--bootstrap must be positive")
    return args


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else project_root() / path


def ensure_outputs(paths: Paths, overwrite: bool) -> Path:
    source_dir = paths.output_dir / "source_data"
    source_dir.mkdir(parents=True, exist_ok=True)
    generated = [
        source_dir / "supplementary_genomic_increment_bootstrap.csv",
        source_dir / "supplementary_five_marker_encoding_metrics.csv",
        source_dir / "supplementary_five_marker_encoding_delta_bootstrap.csv",
        source_dir / "supplementary_five_marker_encoding_predictions.csv",
        paths.output_dir / "supplementary_model_uncertainty_statistics.xlsx",
        paths.output_dir / "supplementary_model_uncertainty_statistics.md",
        paths.output_dir / "supplementary_model_uncertainty_manifest.json",
    ]
    existing = [path for path in generated if path.exists()]
    if existing and not overwrite:
        names = ", ".join(str(path) for path in existing)
        raise FileExistsError(f"Generated output already exists; use --overwrite to replace: {names}")
    return source_dir


def require_columns(df: pd.DataFrame, columns: list[str], context: str) -> None:
    missing = [col for col in columns if col not in df.columns]
    if missing:
        raise ValueError(f"{context} missing required columns: {missing}")


def metric_value(metric: str, y: np.ndarray, prob: np.ndarray) -> float:
    from sklearn.metrics import average_precision_score, brier_score_loss, log_loss, roc_auc_score

    if metric == "AUROC":
        return float(roc_auc_score(y, prob))
    if metric == "AUPRC":
        return float(average_precision_score(y, prob))
    if metric == "Brier":
        return float(brier_score_loss(y, prob))
    if metric == "LogLoss":
        return float(log_loss(y, prob, labels=[0, 1]))
    raise ValueError(f"Unsupported metric: {metric}")


def performance_bundle(y: np.ndarray, prob: np.ndarray) -> dict[str, float]:
    return {metric: metric_value(metric, y, prob) for metric in METRIC_DIRECTIONS}


def percentile_ci(values: list[float] | np.ndarray) -> tuple[float, float]:
    arr = np.asarray(values, dtype=float)
    return float(np.percentile(arr, 2.5)), float(np.percentile(arr, 97.5))


def improvement(metric: str, reference: float, comparator: float) -> float:
    if METRIC_DIRECTIONS[metric] == "higher is better":
        return comparator - reference
    return reference - comparator


def build_outcome_increment_bootstrap(ladder_path: Path, n_bootstrap: int, seed: int) -> pd.DataFrame:
    df = pd.read_csv(ladder_path)
    require_columns(
        df,
        ["strain", "outcome", "split", "observed", LADDER_AST_COL, LADDER_FULL_COL],
        "nested-model predictions",
    )
    test = df[df["split"] == TEST_SPLIT].copy()
    expected = {"mortality_30d", "metastatic_infection"}
    if set(test["outcome"]) != expected:
        raise ValueError(f"Expected outcomes {sorted(expected)} in test split, found {sorted(test['outcome'].unique())}")

    wide = {}
    for outcome in expected:
        sub = test[test["outcome"] == outcome].sort_values("strain").reset_index(drop=True)
        wide[outcome] = sub
    if not wide["mortality_30d"]["strain"].equals(wide["metastatic_infection"]["strain"]):
        raise ValueError("Mortality and invasive phenotype predictions do not align on identical strain order")

    point = {}
    for outcome, sub in wide.items():
        y = sub["observed"].to_numpy(dtype=int)
        ast = sub[LADDER_AST_COL].to_numpy(dtype=float)
        full = sub[LADDER_FULL_COL].to_numpy(dtype=float)
        point[outcome] = {
            metric: improvement(metric, metric_value(metric, y, ast), metric_value(metric, y, full))
            for metric in METRIC_DIRECTIONS
        }

    rng = np.random.default_rng(seed)
    boot = {metric: [] for metric in METRIC_DIRECTIONS}
    n = len(wide["mortality_30d"])
    for _ in range(n_bootstrap):
        idx = rng.integers(0, n, size=n)
        iteration = {}
        valid = True
        for outcome, sub in wide.items():
            y = sub["observed"].to_numpy(dtype=int)[idx]
            if len(np.unique(y)) < 2:
                valid = False
                break
            ast = sub[LADDER_AST_COL].to_numpy(dtype=float)[idx]
            full = sub[LADDER_FULL_COL].to_numpy(dtype=float)[idx]
            iteration[outcome] = {
                metric: improvement(metric, metric_value(metric, y, ast), metric_value(metric, y, full))
                for metric in METRIC_DIRECTIONS
            }
        if not valid:
            continue
        for metric in METRIC_DIRECTIONS:
            boot[metric].append(iteration["metastatic_infection"][metric] - iteration["mortality_30d"][metric])

    rows = []
    for metric, values in boot.items():
        lo, hi = percentile_ci(values)
        rows.append(
            {
                "comparison": "post_AST_full_increment_difference",
                "metric": metric,
                "metric_direction": METRIC_DIRECTIONS[metric],
                "reference_model": "Clinical + AST",
                "comparator_model": "Full model",
                "mortality_increment": point["mortality_30d"][metric],
                "invasive_phenotype_increment": point["metastatic_infection"][metric],
                "difference_in_increment_invasive_minus_mortality": point["metastatic_infection"][metric]
                - point["mortality_30d"][metric],
                "ci_low": lo,
                "ci_high": hi,
                "n": n,
                "mortality_events": int(wide["mortality_30d"]["observed"].sum()),
                "invasive_phenotype_events": int(wide["metastatic_infection"]["observed"].sum()),
                "n_bootstrap_used": len(values),
                "bootstrap_seed": seed,
                "split": TEST_SPLIT,
            }
        )
    return pd.DataFrame(rows)


def add_modeling_contract_to_path() -> None:
    scripts_dir = project_root() / "03_models" / "clinical_genomic_models" / "scripts"
    sys.path.insert(0, str(scripts_dir))


def tune_c_on_validation(discovery: pd.DataFrame, validation: pd.DataFrame, outcome: str, features: list[str]) -> float:
    from modeling_contract import C_CANDIDATES, evaluate_model

    best: tuple[float, float, float, float] | None = None
    best_c = C_CANDIDATES[0]
    for c_value in C_CANDIDATES:
        row, _, _ = evaluate_model(
            discovery,
            validation,
            outcome,
            features,
            "candidate",
            VALIDATION_SPLIT,
            c_value,
            False,
        )
        ranking = (float(row["AUROC"]), -float(row["Brier"]), -float(c_value))
        if best is None or ranking > best:
            best = ranking
            best_c = c_value
    return best_c


def build_five_marker_predictions(features_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    add_modeling_contract_to_path()
    from modeling_contract import (
        selected_clinical_features,
        FIVE_MARKER_BINARY,
        FIVE_MARKERS,
        OUTCOME_LABELS,
        add_derived_predictors,
        evaluate_model,
        split_by_year,
        validate_feature_panel,
    )

    raw = pd.read_csv(features_path, low_memory=False)
    merged = add_derived_predictors(raw)
    splits = split_by_year(merged)

    rows = []
    prediction_tables = []
    for outcome in OUTCOMES:
        label = OUTCOME_LABELS[outcome]
        clinical = selected_clinical_features(outcome)
        panels = {
            "baseline": clinical,
            "five_markers_separate": [*clinical, *FIVE_MARKERS],
            "five_marker_binary_all_partial": [*clinical, *FIVE_MARKER_BINARY],
        }
        validate_feature_panel(merged, panels)
        tuned_c = {
            model_name: tune_c_on_validation(splits["discovery_2013_2021"], splits[VALIDATION_SPLIT], outcome, features)
            for model_name, features in panels.items()
        }
        for split, eval_df, train_df in [
            (VALIDATION_SPLIT, splits[VALIDATION_SPLIT], splits["discovery_2013_2021"]),
            (TEST_SPLIT, splits[TEST_SPLIT], splits["discovery_2013_2021"]),
        ]:
            pred = eval_df[[col for col in ["strain", "年份"] if col in eval_df.columns]].copy()
            pred["outcome"] = label
            pred["split"] = split
            pred["observed"] = eval_df[outcome].to_numpy(dtype=int)
            for model_name, model_features in panels.items():
                row, prob, _ = evaluate_model(
                    train_df,
                    eval_df,
                    outcome,
                    model_features,
                    model_name,
                    split,
                    tuned_c[model_name],
                    False,
                )
                row["model_label"] = FIVE_MARKER_LABELS[model_name]
                row["outcome_label"] = OUTCOME_LABELS_FOR_TABLE[label]
                row["c_strategy"] = "validation_auroc_tuned"
                rows.append(row)
                pred[f"{model_name}_prob"] = prob
            prediction_tables.append(pred)
    return pd.DataFrame(rows), pd.concat(prediction_tables, ignore_index=True)


def bootstrap_five_marker_tables(predictions: pd.DataFrame, n_bootstrap: int, seed: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    metrics_rows = []
    delta_rows = []
    test = predictions[predictions["split"] == TEST_SPLIT].copy()
    require_columns(test, ["outcome", "observed", *FIVE_MARKER_MODELS.values()], "hypervirulence-marker predictions")

    for outcome, sub in test.groupby("outcome", sort=True):
        sub = sub.reset_index(drop=True)
        y = sub["observed"].to_numpy(dtype=int)
        probs = {model: sub[col].to_numpy(dtype=float) for model, col in FIVE_MARKER_MODELS.items()}
        point = {model: performance_bundle(y, prob) for model, prob in probs.items()}
        boot_model = {model: {metric: [] for metric in METRIC_DIRECTIONS} for model in probs}
        boot_delta = {metric: [] for metric in METRIC_DIRECTIONS}

        for _ in range(n_bootstrap):
            idx = rng.integers(0, len(sub), size=len(sub))
            yb = y[idx]
            if len(np.unique(yb)) < 2:
                continue
            iter_metrics = {model: performance_bundle(yb, prob[idx]) for model, prob in probs.items()}
            for model, values in iter_metrics.items():
                for metric, value in values.items():
                    boot_model[model][metric].append(value)
            for metric in METRIC_DIRECTIONS:
                boot_delta[metric].append(
                    iter_metrics["five_markers_separate"][metric]
                    - iter_metrics["five_marker_binary_all_partial"][metric]
                )

        for model, values in point.items():
            for metric, estimate in values.items():
                lo, hi = percentile_ci(boot_model[model][metric])
                metrics_rows.append(
                    {
                        "outcome": outcome,
                        "model": model,
                        "model_label": FIVE_MARKER_LABELS[model],
                        "metric": metric,
                        "metric_direction": METRIC_DIRECTIONS[metric],
                        "n": len(sub),
                        "events": int(y.sum()),
                        "estimate": estimate,
                        "ci_low": lo,
                        "ci_high": hi,
                        "n_bootstrap_used": len(boot_model[model][metric]),
                        "outcome_label": OUTCOME_LABELS_FOR_TABLE[outcome],
                        "split": TEST_SPLIT,
                    }
                )

        for metric, values in boot_delta.items():
            lo, hi = percentile_ci(values)
            delta_rows.append(
                {
                    "outcome": outcome,
                    "outcome_label": OUTCOME_LABELS_FOR_TABLE[outcome],
                    "contrast": "five_markers_separate - five_marker_binary_all_partial",
                    "metric": metric,
                    "metric_direction": METRIC_DIRECTIONS[metric],
                    "separate_estimate": point["five_markers_separate"][metric],
                    "compressed_estimate": point["five_marker_binary_all_partial"][metric],
                    "difference_separate_minus_compressed": point["five_markers_separate"][metric]
                    - point["five_marker_binary_all_partial"][metric],
                    "ci_low": lo,
                    "ci_high": hi,
                    "n": len(sub),
                    "events": int(y.sum()),
                    "n_bootstrap_used": len(values),
                    "bootstrap_seed": seed,
                    "split": TEST_SPLIT,
                }
            )
    return pd.DataFrame(metrics_rows), pd.DataFrame(delta_rows)


def write_plain_xlsx(output_path: Path, sheets: dict[str, pd.DataFrame]) -> None:
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        for sheet, table in sheets.items():
            table.to_excel(writer, sheet_name=sheet, index=False)


def write_markdown_summary(output_path: Path, outcome_increment: pd.DataFrame, marker_delta: pd.DataFrame) -> None:
    auroc_row = outcome_increment[outcome_increment["metric"] == "AUROC"].iloc[0]
    brier_row = outcome_increment[outcome_increment["metric"] == "Brier"].iloc[0]
    logloss_row = outcome_increment[outcome_increment["metric"] == "LogLoss"].iloc[0]
    marker_row = marker_delta[
        (marker_delta["outcome"] == "metastatic_infection") & (marker_delta["metric"] == "AUROC")
    ].iloc[0]
    text = f"""# Supplementary model uncertainty statistics

Plain-language summary:

- From Clinical + AST to the full model, the AUROC increment was {auroc_row['invasive_phenotype_increment']:.3f} for liver abscess or metastatic infection and {auroc_row['mortality_increment']:.3f} for 30-day mortality. The paired difference in increments was {auroc_row['difference_in_increment_invasive_minus_mortality']:.3f} (95% CI {auroc_row['ci_low']:.3f} to {auroc_row['ci_high']:.3f}).
- The corresponding Brier-score error reduction difference was {brier_row['difference_in_increment_invasive_minus_mortality']:.3f} (95% CI {brier_row['ci_low']:.3f} to {brier_row['ci_high']:.3f}); the log-loss error reduction difference was {logloss_row['difference_in_increment_invasive_minus_mortality']:.3f} (95% CI {logloss_row['ci_low']:.3f} to {logloss_row['ci_high']:.3f}).
- For liver abscess or metastatic infection, individual-marker encoding exceeded compressed-status encoding by {marker_row['difference_separate_minus_compressed']:.3f} AUROC (95% CI {marker_row['ci_low']:.3f} to {marker_row['ci_high']:.3f}).

Bootstrap contract:

- Independent unit: patient/strain record in the 2024-2025 temporal test split.
- Resampling: paired patient-level bootstrap with replacement.
- Point estimates: locked nested-model predictions; 2013-2021 training, 2022-2023 validation and 2024-2025 temporal test split for hypervirulence-marker encoding.
- Positive increments for AUROC/AUPRC mean higher discrimination. Positive increments for Brier and log loss mean lower prediction error.
"""
    output_path.write_text(text, encoding="utf-8")


def run(args: argparse.Namespace) -> None:
    paths = Paths(
        features=resolve_path(args.features),
        ladder_predictions=resolve_path(args.ladder_predictions),
        output_dir=resolve_path(args.output_dir),
    )
    source_dir = ensure_outputs(paths, args.overwrite)

    outcome_increment = build_outcome_increment_bootstrap(paths.ladder_predictions, args.bootstrap, args.seed)
    add_modeling_contract_to_path()
    from modeling_contract import load_clinical_selection
    load_clinical_selection(args.clinical_selection or paths.ladder_predictions.parent / "clinical_selection.json")
    marker_performance, marker_predictions = build_five_marker_predictions(paths.features)
    marker_metrics, marker_delta = bootstrap_five_marker_tables(marker_predictions, args.bootstrap, args.seed)

    outcome_increment.to_csv(source_dir / "supplementary_genomic_increment_bootstrap.csv", index=False)
    marker_metrics.to_csv(source_dir / "supplementary_five_marker_encoding_metrics.csv", index=False)
    marker_delta.to_csv(source_dir / "supplementary_five_marker_encoding_delta_bootstrap.csv", index=False)
    marker_predictions.to_csv(source_dir / "supplementary_five_marker_encoding_predictions.csv", index=False)

    readme = pd.DataFrame(
        [
            {
                "sheet": "OutcomeIncrement",
                "contents": "Paired bootstrap of AST-to-full model increments and the invasive-minus-mortality difference.",
            },
            {
                "sheet": "FiveMarkerMetrics",
                "contents": "AUROC, AUPRC, Brier and log-loss estimates for baseline, five individual markers, and compressed-status encodings.",
            },
            {
                "sheet": "FiveMarkerDelta",
                "contents": "Paired bootstrap contrast of individual-marker encoding minus compressed-status encoding.",
            },
        ]
    )
    write_plain_xlsx(
        paths.output_dir / "supplementary_model_uncertainty_statistics.xlsx",
        {
            "README": readme,
            "OutcomeIncrement": outcome_increment,
            "FiveMarkerMetrics": marker_metrics,
            "FiveMarkerDelta": marker_delta,
        },
    )
    write_markdown_summary(
        paths.output_dir / "supplementary_model_uncertainty_statistics.md",
        outcome_increment,
        marker_delta,
    )

    if args.update_figure2_source:
        figure_source = project_root() / "submit" / "figure" / "source_data" / "figure2_marker_encoding_auroc_source.csv"
        marker_metrics[marker_metrics["metric"] == "AUROC"][
            [
                "outcome",
                "model",
                "model_label",
                "metric",
                "n",
                "events",
                "estimate",
                "ci_low",
                "ci_high",
                "n_bootstrap_used",
                "outcome_label",
            ]
        ].to_csv(figure_source, index=False)

    manifest = {
        "features": str(paths.features),
        "ladder_predictions": str(paths.ladder_predictions),
        "split": TEST_SPLIT,
        "n_bootstrap": args.bootstrap,
        "seed": args.seed,
        "ci_method": "patient-level paired bootstrap percentile 95% CI",
        "updated_figure2_source": bool(args.update_figure2_source),
        "generated_files": [
            "source_data/supplementary_genomic_increment_bootstrap.csv",
            "source_data/supplementary_five_marker_encoding_metrics.csv",
            "source_data/supplementary_five_marker_encoding_delta_bootstrap.csv",
            "source_data/supplementary_five_marker_encoding_predictions.csv",
            "supplementary_model_uncertainty_statistics.xlsx",
            "supplementary_model_uncertainty_statistics.md",
            "supplementary_model_uncertainty_manifest.json",
        ],
    }
    (paths.output_dir / "supplementary_model_uncertainty_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print("Outcome-specific post-AST increment difference:")
    print(outcome_increment.round(4).to_string(index=False))
    print("\nHypervirulence-marker encoding paired differences:")
    print(marker_delta.round(4).to_string(index=False))
    print(f"\nWrote supplementary tables to: {paths.output_dir}")


def main() -> None:
    args = parse_args(sys.argv[1:])
    if args is None:
        return
    run(args)


if __name__ == "__main__":
    main()
